name: Code Analysis
on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube

    steps:
      - name: Checkout Source Files
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        timeout-minutes: 10
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://quality.nhcarrigan.com"
        with:
          args: >
            -Dsonar.sources=.
            -Dsonar.projectKey=website-headers

      - name: SonarQube Quality Gate check
        uses: sonarsource/sonarqube-quality-gate-action@v1
        with:
          pollingTimeoutSec: 600
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: "https://quality.nhcarrigan.com"
